// <auto-generated />
using System;
using BookNumAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookNumAPI.Migrations
{
    [DbContext(typeof(BookNumApiContext))]
    [Migration("20260303070032_AddActivityGoogleFields")]
    partial class AddActivityGoogleFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookNumAPI.Models.Account", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AccountID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountId"));

                    b.Property<string>("Account1")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Account");

                    b.Property<string>("AuthProvider")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("AuthProviderId")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("AuthProviderID");

                    b.Property<DateTime?>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool?>("IsEmailVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime");

                    b.Property<string>("LastLoginIp")
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("LastLoginIP");

                    b.Property<string>("Password")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Role")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int?>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime");

                    b.HasKey("AccountId")
                        .HasName("PK__Account__349DA5862ADDCBE4");

                    b.ToTable("Account", (string)null);
                });

            modelBuilder.Entity("BookNumAPI.Models.Activity", b =>
                {
                    b.Property<int>("ActivityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ActivityID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ActivityId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("CategoryID");

                    b.Property<DateTime>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("EndAt")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("datetime");

                    b.Property<string>("GoogleEventId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("GoogleSyncedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Image")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("MaxPeople")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("datetime");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("ActivityId")
                        .HasName("PK__Activity__45F4A7F1272FEF8C");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Activity", (string)null);
                });

            modelBuilder.Entity("BookNumAPI.Models.ActivityCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CategoryID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("CategoryId")
                        .HasName("PK__Activity__19093A2BB741AC74");

                    b.HasIndex(new[] { "CategoryName" }, "UQ__Activity__8517B2E0C7A91DEB")
                        .IsUnique();

                    b.HasIndex(new[] { "CategoryName" }, "UQ__Activity__8517B2E0EEB13798")
                        .IsUnique();

                    b.ToTable("ActivityCategory", (string)null);
                });

            modelBuilder.Entity("BookNumAPI.Models.Chat", b =>
                {
                    b.Property<int>("ChatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ChatID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChatId"));

                    b.Property<int>("MatchedId")
                        .HasColumnType("int")
                        .HasColumnName("MatchedID");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("ReceiverId")
                        .HasColumnType("int")
                        .HasColumnName("ReceiverID");

                    b.Property<DateTime>("SendAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("SenderId")
                        .HasColumnType("int")
                        .HasColumnName("SenderID");

                    b.HasKey("ChatId")
                        .HasName("PK__Chat__A9FBE626BC1F18E6");

                    b.HasIndex("MatchedId");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("Chat", (string)null);
                });

            modelBuilder.Entity("BookNumAPI.Models.CityPreference", b =>
                {
                    b.Property<int>("CityPreferencesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CityPreferencesID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CityPreferencesId"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("CityPreferencesId")
                        .HasName("PK__CityPref__BB954C5A6EDCC5CA");

                    b.HasIndex("UserId");

                    b.ToTable("CityPreferences");
                });

            modelBuilder.Entity("BookNumAPI.Models.GoogleCalendarToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("GoogleCalendarTokens");
                });

            modelBuilder.Entity("BookNumAPI.Models.Hobby", b =>
                {
                    b.Property<int>("HobbyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("HobbyID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HobbyId"));

                    b.Property<int>("HobbyCategoryId")
                        .HasColumnType("int")
                        .HasColumnName("HobbyCategoryID");

                    b.Property<string>("HobbyName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("IsActived")
                        .HasColumnType("bit");

                    b.HasKey("HobbyId")
                        .HasName("PK__Hobby__0ABE0BEFC270586B");

                    b.HasIndex("HobbyCategoryId");

                    b.ToTable("Hobby", (string)null);
                });

            modelBuilder.Entity("BookNumAPI.Models.HobbyCategory", b =>
                {
                    b.Property<int>("HobbyCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("HobbyCategoryID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HobbyCategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("HobbyCategoryId")
                        .HasName("PK__HobbyCat__4D6D66CB96B79E10");

                    b.ToTable("HobbyCategory", (string)null);
                });

            modelBuilder.Entity("BookNumAPI.Models.HobbyList", b =>
                {
                    b.Property<int>("HobbyListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("HobbyListID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HobbyListId"));

                    b.Property<int>("HobbyId")
                        .HasColumnType("int")
                        .HasColumnName("HobbyID");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("HobbyListId")
                        .HasName("PK__HobbyLis__12197A4B28EA0910");

                    b.HasIndex("HobbyId");

                    b.HasIndex("UserId");

                    b.ToTable("HobbyList", (string)null);
                });

            modelBuilder.Entity("BookNumAPI.Models.Info", b =>
                {
                    b.Property<int>("InfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("InfoID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InfoId"));

                    b.Property<int?>("AgeMax")
                        .HasColumnType("int");

                    b.Property<int?>("AgeMin")
                        .HasColumnType("int");

                    b.Property<string>("Bio")
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.Property<string>("CurrentCity")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("GenderPrefer")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Height")
                        .HasColumnType("decimal(5, 1)");

                    b.Property<string>("Job")
                        .HasMaxLength(20)
                        .HasColumnType("nchar(20)")
                        .IsFixedLength();

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(9, 6)");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(9, 6)");

                    b.Property<string>("Nickname")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Photo")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("decimal(5, 1)");

                    b.HasKey("InfoId")
                        .HasName("PK__Info__4DEC9D9A06EAE76E");

                    b.HasIndex("UserId");

                    b.ToTable("Info", (string)null);
                });

            modelBuilder.Entity("BookNumAPI.Models.Liked", b =>
                {
                    b.Property<int>("LikedId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LikedID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LikedId"));

                    b.Property<DateTime>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool>("IsLiked")
                        .HasColumnType("bit");

                    b.Property<int>("LikedUserId")
                        .HasColumnType("int")
                        .HasColumnName("LikedUserID");

                    b.Property<int>("LikerUserId")
                        .HasColumnType("int")
                        .HasColumnName("LikerUserID");

                    b.Property<double>("Score")
                        .HasColumnType("float");

                    b.HasKey("LikedId")
                        .HasName("PK__Liked__A7917838E26C9574");

                    b.HasIndex("LikedUserId");

                    b.HasIndex("LikerUserId");

                    b.ToTable("Liked", (string)null);
                });

            modelBuilder.Entity("BookNumAPI.Models.Matched", b =>
                {
                    b.Property<int>("MatchedId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MatchedID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MatchedId"));

                    b.Property<DateTime>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<double>("Score")
                        .HasColumnType("float");

                    b.Property<DateTime?>("UnMatchAt")
                        .HasColumnType("datetime");

                    b.Property<int>("User1Id")
                        .HasColumnType("int")
                        .HasColumnName("User1ID");

                    b.Property<int?>("User1LastReadMessageId")
                        .HasColumnType("int");

                    b.Property<int>("User2Id")
                        .HasColumnType("int")
                        .HasColumnName("User2ID");

                    b.Property<int?>("User2LastReadMessageId")
                        .HasColumnType("int");

                    b.HasKey("MatchedId")
                        .HasName("PK__Matched__F618116B4FCC2B9D");

                    b.HasIndex("User1Id");

                    b.HasIndex("User2Id");

                    b.ToTable("Matched", (string)null);
                });

            modelBuilder.Entity("BookNumAPI.Models.Method", b =>
                {
                    b.Property<int>("MethodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MethodID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MethodId"));

                    b.Property<int>("DurationDay")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActived")
                        .HasColumnType("bit");

                    b.Property<string>("MethodName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PayPalId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PayPalID");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("MethodId")
                        .HasName("PK__Method__FC681FB1FDD2702C");

                    b.ToTable("Method", (string)null);
                });

            modelBuilder.Entity("BookNumAPI.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("OrderID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<DateOnly>("AppointmentDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<TimeOnly>("EndAt")
                        .HasColumnType("time");

                    b.Property<string>("OrderNo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("OrderStatus")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PayAt")
                        .HasColumnType("datetime");

                    b.Property<string>("PayMethod")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("PayStatus")
                        .HasColumnType("int");

                    b.Property<int>("RenterId")
                        .HasColumnType("int")
                        .HasColumnName("RenterID");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int")
                        .HasColumnName("ServiceID");

                    b.Property<TimeOnly>("StartAt")
                        .HasColumnType("time");

                    b.Property<int>("TotalAmount")
                        .HasColumnType("int");

                    b.Property<string>("TransactionNo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("OrderId")
                        .HasName("PK__Orders__C3905BAFCE519266");

                    b.HasIndex("RenterId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("BookNumAPI.Models.OrderLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LogID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("OldStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("OrderID");

                    b.Property<DateTime>("UpdateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("LogId")
                        .HasName("PK__OrderLog__5E5499A81A105201");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderLog", (string)null);
                });

            modelBuilder.Entity("BookNumAPI.Models.Participant", b =>
                {
                    b.Property<int>("ParticipantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ParticipantID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ParticipantId"));

                    b.Property<int>("ActivityId")
                        .HasColumnType("int")
                        .HasColumnName("ActivityID");

                    b.Property<DateTime>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("JoinStatus")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("ParticipantId")
                        .HasName("PK__Particip__7227997E8D08595A");

                    b.HasIndex("ActivityId");

                    b.HasIndex("UserId");

                    b.ToTable("Participant", (string)null);
                });

            modelBuilder.Entity("BookNumAPI.Models.Premium", b =>
                {
                    b.Property<int>("PremiumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PremiumID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PremiumId"));

                    b.Property<bool>("AutoRenew")
                        .HasColumnType("bit");

                    b.Property<DateTime>("EndAt")
                        .HasColumnType("datetime");

                    b.Property<int>("MethodId")
                        .HasColumnType("int")
                        .HasColumnName("MethodID");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("datetime");

                    b.Property<string>("SubscriptionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SubscriptionID");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("PremiumId")
                        .HasName("PK__Premium__86B646E54FD4B798");

                    b.HasIndex("MethodId");

                    b.HasIndex("UserId");

                    b.ToTable("Premium", (string)null);
                });

            modelBuilder.Entity("BookNumAPI.Models.Renter", b =>
                {
                    b.Property<int>("RenterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RenterID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RenterId"));

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<decimal?>("Height")
                        .HasColumnType("decimal(5, 1)");

                    b.Property<int>("HrRate")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("RenterName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StyleTag")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("decimal(5, 1)");

                    b.HasKey("RenterId")
                        .HasName("PK__Renters__921D6FFF1A311609");

                    b.ToTable("Renters");
                });

            modelBuilder.Entity("BookNumAPI.Models.RenterPhoto", b =>
                {
                    b.Property<int>("PhotoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PhotoID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PhotoId"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsMain")
                        .HasColumnType("bit");

                    b.Property<int>("RenterId")
                        .HasColumnType("int")
                        .HasColumnName("RenterID");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("PhotoId")
                        .HasName("PK__RenterPh__21B7B5823FCE75E5");

                    b.HasIndex("RenterId");

                    b.ToTable("RenterPhotos");
                });

            modelBuilder.Entity("BookNumAPI.Models.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ReviewID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewId"));

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("OrderID");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("ReviewId")
                        .HasName("PK__Reviews__74BC79AE5A82892C");

                    b.HasIndex("OrderId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("BookNumAPI.Models.Service", b =>
                {
                    b.Property<int>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ServiceID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServiceId"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Hour")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ServiceId")
                        .HasName("PK__Services__C51BB0EA17A4391B");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("BookNumAPI.Models.Token", b =>
                {
                    b.Property<int>("TokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TokenId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime>("ExpiryAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Token1")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Token");

                    b.Property<int>("TokenType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("datetime");

                    b.HasKey("TokenId")
                        .HasName("PK__Token__658FEEEAC489AB32");

                    b.HasIndex("AccountId");

                    b.ToTable("Token", (string)null);
                });

            modelBuilder.Entity("BookNumAPI.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int")
                        .HasColumnName("AccountID");

                    b.Property<DateOnly?>("Birthdate")
                        .HasColumnType("date");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("UserId")
                        .HasName("PK__User__1788CCAC5462CFCC");

                    b.HasIndex("AccountId");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("BookNumAPI.Models.Activity", b =>
                {
                    b.HasOne("BookNumAPI.Models.ActivityCategory", "Category")
                        .WithMany("Activities")
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("FK_Activity_Category");

                    b.HasOne("BookNumAPI.Models.User", "User")
                        .WithMany("Activities")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Activity_User");

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BookNumAPI.Models.Chat", b =>
                {
                    b.HasOne("BookNumAPI.Models.Matched", "Matched")
                        .WithMany("Chats")
                        .HasForeignKey("MatchedId")
                        .IsRequired()
                        .HasConstraintName("FK_Chat_Matched");

                    b.HasOne("BookNumAPI.Models.User", "Receiver")
                        .WithMany("ChatReceivers")
                        .HasForeignKey("ReceiverId")
                        .IsRequired()
                        .HasConstraintName("FK_Chat_Receiver");

                    b.HasOne("BookNumAPI.Models.User", "Sender")
                        .WithMany("ChatSenders")
                        .HasForeignKey("SenderId")
                        .IsRequired()
                        .HasConstraintName("FK_Chat_Sender");

                    b.Navigation("Matched");

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("BookNumAPI.Models.CityPreference", b =>
                {
                    b.HasOne("BookNumAPI.Models.User", "User")
                        .WithMany("CityPreferences")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_CityPref_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BookNumAPI.Models.Hobby", b =>
                {
                    b.HasOne("BookNumAPI.Models.HobbyCategory", "HobbyCategory")
                        .WithMany("Hobbies")
                        .HasForeignKey("HobbyCategoryId")
                        .IsRequired()
                        .HasConstraintName("FK_Hobby_Category");

                    b.Navigation("HobbyCategory");
                });

            modelBuilder.Entity("BookNumAPI.Models.HobbyList", b =>
                {
                    b.HasOne("BookNumAPI.Models.Hobby", "Hobby")
                        .WithMany("HobbyLists")
                        .HasForeignKey("HobbyId")
                        .IsRequired()
                        .HasConstraintName("FK_HobbyList_Hobby");

                    b.HasOne("BookNumAPI.Models.User", "User")
                        .WithMany("HobbyLists")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_HobbyList_User");

                    b.Navigation("Hobby");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BookNumAPI.Models.Info", b =>
                {
                    b.HasOne("BookNumAPI.Models.User", "User")
                        .WithMany("Infos")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Info_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BookNumAPI.Models.Liked", b =>
                {
                    b.HasOne("BookNumAPI.Models.User", "LikedUser")
                        .WithMany("LikedLikedUsers")
                        .HasForeignKey("LikedUserId")
                        .IsRequired()
                        .HasConstraintName("FK_Liked_Liked");

                    b.HasOne("BookNumAPI.Models.User", "LikerUser")
                        .WithMany("LikedLikerUsers")
                        .HasForeignKey("LikerUserId")
                        .IsRequired()
                        .HasConstraintName("FK_Liked_Liker");

                    b.Navigation("LikedUser");

                    b.Navigation("LikerUser");
                });

            modelBuilder.Entity("BookNumAPI.Models.Matched", b =>
                {
                    b.HasOne("BookNumAPI.Models.User", "User1")
                        .WithMany("MatchedUser1s")
                        .HasForeignKey("User1Id")
                        .IsRequired()
                        .HasConstraintName("FK_Matched_User1");

                    b.HasOne("BookNumAPI.Models.User", "User2")
                        .WithMany("MatchedUser2s")
                        .HasForeignKey("User2Id")
                        .IsRequired()
                        .HasConstraintName("FK_Matched_User2");

                    b.Navigation("User1");

                    b.Navigation("User2");
                });

            modelBuilder.Entity("BookNumAPI.Models.Order", b =>
                {
                    b.HasOne("BookNumAPI.Models.Renter", "Renter")
                        .WithMany("Orders")
                        .HasForeignKey("RenterId")
                        .IsRequired()
                        .HasConstraintName("FK_Orders_Renters");

                    b.HasOne("BookNumAPI.Models.Service", "Service")
                        .WithMany("Orders")
                        .HasForeignKey("ServiceId")
                        .IsRequired()
                        .HasConstraintName("FK_Orders_Services");

                    b.HasOne("BookNumAPI.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Orders_User");

                    b.Navigation("Renter");

                    b.Navigation("Service");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BookNumAPI.Models.OrderLog", b =>
                {
                    b.HasOne("BookNumAPI.Models.Order", "Order")
                        .WithMany("OrderLogs")
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("FK_OrderHistory_Orders");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("BookNumAPI.Models.Participant", b =>
                {
                    b.HasOne("BookNumAPI.Models.Activity", "Activity")
                        .WithMany("Participants")
                        .HasForeignKey("ActivityId")
                        .IsRequired()
                        .HasConstraintName("FK_Participant_Activity");

                    b.HasOne("BookNumAPI.Models.User", "User")
                        .WithMany("Participants")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Participant_User");

                    b.Navigation("Activity");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BookNumAPI.Models.Premium", b =>
                {
                    b.HasOne("BookNumAPI.Models.Method", "Method")
                        .WithMany("Premia")
                        .HasForeignKey("MethodId")
                        .IsRequired()
                        .HasConstraintName("FK_Premium_Method");

                    b.HasOne("BookNumAPI.Models.User", "User")
                        .WithMany("Premia")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Premium_User");

                    b.Navigation("Method");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BookNumAPI.Models.RenterPhoto", b =>
                {
                    b.HasOne("BookNumAPI.Models.Renter", "Renter")
                        .WithMany("RenterPhotos")
                        .HasForeignKey("RenterId")
                        .IsRequired()
                        .HasConstraintName("FK_RenterPhotos_Renters");

                    b.Navigation("Renter");
                });

            modelBuilder.Entity("BookNumAPI.Models.Review", b =>
                {
                    b.HasOne("BookNumAPI.Models.Order", "Order")
                        .WithMany("Reviews")
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("FK_Reviews_Orders");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("BookNumAPI.Models.Token", b =>
                {
                    b.HasOne("BookNumAPI.Models.Account", "Account")
                        .WithMany("Tokens")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserTokens_Account");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("BookNumAPI.Models.User", b =>
                {
                    b.HasOne("BookNumAPI.Models.Account", "Account")
                        .WithMany("Users")
                        .HasForeignKey("AccountId")
                        .IsRequired()
                        .HasConstraintName("FK_User_Account");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("BookNumAPI.Models.Account", b =>
                {
                    b.Navigation("Tokens");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("BookNumAPI.Models.Activity", b =>
                {
                    b.Navigation("Participants");
                });

            modelBuilder.Entity("BookNumAPI.Models.ActivityCategory", b =>
                {
                    b.Navigation("Activities");
                });

            modelBuilder.Entity("BookNumAPI.Models.Hobby", b =>
                {
                    b.Navigation("HobbyLists");
                });

            modelBuilder.Entity("BookNumAPI.Models.HobbyCategory", b =>
                {
                    b.Navigation("Hobbies");
                });

            modelBuilder.Entity("BookNumAPI.Models.Matched", b =>
                {
                    b.Navigation("Chats");
                });

            modelBuilder.Entity("BookNumAPI.Models.Method", b =>
                {
                    b.Navigation("Premia");
                });

            modelBuilder.Entity("BookNumAPI.Models.Order", b =>
                {
                    b.Navigation("OrderLogs");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("BookNumAPI.Models.Renter", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("RenterPhotos");
                });

            modelBuilder.Entity("BookNumAPI.Models.Service", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("BookNumAPI.Models.User", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("ChatReceivers");

                    b.Navigation("ChatSenders");

                    b.Navigation("CityPreferences");

                    b.Navigation("HobbyLists");

                    b.Navigation("Infos");

                    b.Navigation("LikedLikedUsers");

                    b.Navigation("LikedLikerUsers");

                    b.Navigation("MatchedUser1s");

                    b.Navigation("MatchedUser2s");

                    b.Navigation("Orders");

                    b.Navigation("Participants");

                    b.Navigation("Premia");
                });
#pragma warning restore 612, 618
        }
    }
}
